apiVersion: apps/v1
kind: Deployment
metadata:
  name: acr-deployment
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: acr-deploy
        image: ${{ secrets.ACR_LOGIN_SERVER }}.azurecr.io//${{ env.APP_NAME }}:${{ github.sha }}
        ports:
        - containerPort: 80
