# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Deploy

on:
  push:
    branches: [ master ]

env:
  AZURE_RESOURCE_GROUP:  ${{ secrets.RESOURCE_GROUP }}
  AZURE_CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Configure Docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/myapp:${{ github.sha }} .
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/myapp:${{ github.sha }}

      - name: Azure CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure subscription
        run: az account set --subscription ${{ secrets.SUBSCRIPTION }}

      - name: Configure AKS credentials
        run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }}

      - name: Deploy to AKS
        run: |
          kubectl apply -f kubernetes/manifests

